version: '2.4'
services:
  procon1:
    container_name: procon1
    build:
      context: .
    image: procon/procon:1.0
    restart: unless-stopped
    ports:
      # format: localPort:containerPort
      - 27260:27260
    volumes:
      - type: bind
        source: ./Config1
        target: /procon/Configs
      - type: bind
        source: ./Plugins
        target: /procon/Plugins
      # - type: bind
      #   source: ./Logs
      #   target: /procon/Logs
    tty: true

    # create a service for each BF server with its own Config folder
    # procon2:
    #   container_name: procon2
    #   build:
    #     context: .
    #   image: procon/procon:1.0
    #   restart: unless-stopped
    #   ports:
    #     # format: localPort:containerPort
    #     - 27261:27260
    #   volumes:
    #     - type: bind
    #       source: ./Config2
    #       target: /procon/Configs
    #     - type: bind
    #       source: ./Plugins
    #       target: /procon/Plugins
    #     # - type: bind
    #     #   source: ./Logs
    #     #   target: /procon/Logs
    #   tty: true
